import pandas as pd
# Create a dictionary with detailed information for each week of pregnancy
pregnancy_weeks = {
    "Week": list(range(1, 41)),
    "Description": [
        "Fertilization occurs, and the zygote forms.",
        "The zygote becomes a blastocyst and implants in the uterine wall.",
        "The embryo starts to form, and the placenta begins to develop.",
        "The neural tube closes, and the heart starts to beat.",
        "The embryo's major organs and structures begin to form.",
        "The embryo's facial features start to develop.",
        "The embryo's limbs and fingers begin to form.",
        "The embryo's major organs continue to develop.",
        "The embryo becomes a fetus, and the tail disappears.",
        "The fetus's vital organs are fully formed and functioning.",
        "The fetus's genitals begin to develop.",
        "The fetus's fingers and toes are fully formed.",
        "The fetus's bones start to harden.",
        "The fetus's hair and eyebrows begin to grow.",
        "The fetus can make facial expressions.",
        "The fetus's eyes can move, and it can hear sounds.",
        "The fetus's lungs continue to develop.",
        "The fetus's digestive system is fully formed.",
        "The fetus's skin is covered in a protective coating called vernix.",
        "The fetus's movements become more coordinated.",
        "The fetus's bone marrow starts making blood cells.",
        "The fetus's taste buds are developed.",
        "The fetus's lungs produce surfactant, which helps them expand after birth.",
        "The fetus's brain is rapidly developing.",
        "The fetus's eyes can open and close, and it can respond to light.",
        "The fetus's immune system is developing.",
        "The fetus's lungs are fully developed but not yet mature.",
        "The fetus gains weight rapidly.",
        "The fetus's brain continues to develop rapidly.",
        "The fetus's bones are fully developed but still soft.",
        "The fetus moves into a head-down position in preparation for birth.",
        "The fetus gains more weight and body fat.",
        "The fetus practices breathing movements.",
        "The fetus's skin becomes less wrinkled as it gains more fat.",
        "The fetus's brain and nervous system are fully developed.",
        "The fetus continues to gain weight and prepare for birth.",
        "The fetus moves lower into the pelvis in preparation for birth.",
        "The fetus is considered full-term at 37 weeks and can be born any day now.",
        "The placenta provides antibodies to the fetus for protection after birth.",
        "Labor may begin at any time as the body prepares for childbirth."
    ],
    "Baby Size (cm)": [
        0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.6,
        2.3, 3.1, 4.1, 5.4, 7.4, 8.7, 11.6, 13.0, 14.2, 16.4,
        18.1, 19.7, 21.1, 22.4, 23.9, 25.6, 27.3, 28.9, 30.5, 34.6,
        36.6, 37.6, 39.9, 41.1, 42.4, 43.7, 45.0, 46.2, 47.4, 48.6
    ],
    "Baby Weight (g)": [
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2, 4,
        7, 14, 23, 43, 70, 100, 140, 190, 240, 300,
        360, 430, 500, 600, 660, 760, 875, 1000, 1150, 1300,
        1500, 1700, 1900, 2100, 2400, 2600, 2900, 3100, 3300, 3500
    ],
    "Baby Size Comparison": [
        "Size of a poppy seed", "Size of a sesame seed", "Size of a lentil", "Size of a blueberry", "Size of a kidney bean", 
        "Size of a grape", "Size of a kumquat", "Size of a fig", "Size of a lime", "Size of a pea pod", 
        "Size of a lemon", "Size of an apple", "Size of an avocado", "Size of a turnip", "Size of a bell pepper", 
        "Size of a tomato", "Size of a banana", "Size of a carrot", "Size of a spaghetti squash", "Size of a large mango", 
        "Size of an ear of corn", "Size of a rutabaga", "Size of a scallion", "Size of a cauliflower", "Size of a large eggplant", 
        "Size of a butternut squash", "Size of a large cabbage", "Size of a coconut", "Size of a jicama", "Size of a pineapple", 
        "Size of a cantaloupe", "Size of a honeydew melon", "Size of a head of romaine lettuce", "Size of a bunch of Swiss chard", 
        "Size of a leek", "Size of a mini watermelon", "Size of a small pumpkin"
    ],
    "Mother's Body Changes": [
        "Hormonal changes begin as the body prepares for pregnancy.",
        "Implantation bleeding may occur; hormone levels rise.",
        "Morning sickness and fatigue are common.",
        "Breast tenderness and frequent urination begin.",
        "Increased blood volume; hormonal changes continue.",
        "The uterus expands; weight gain may start.",
        "Increased appetite; possible food cravings.",
        "The belly starts to show; skin changes may occur.",
        "Increased energy levels; reduced morning sickness.",
        "The belly continues to grow; mother may feel fetal movements.",
        "Increased blood flow; possible varicose veins.",
        "Mother may experience back pain; leg cramps.",
        "Belly becomes more prominent; stretch marks may appear.",
        "Mother may experience shortness of breath; heartburn.",
        "Belly continues to grow; mother may feel Braxton Hicks contractions.",
        "Mother may experience swelling in hands and feet.",
        "Mother may feel more tired; difficulty sleeping.",
        "Belly continues to grow; mother may experience pelvic pain.",
        "Increased vaginal discharge.",
        "More frequent fetal movements.",
        "Increased back pain; difficulty moving.",
        "Mother may feel more tired; difficulty sleeping.",
        "Increased heartburn and indigestion.",
        "More frequent fetal movements.",
        "Increased swelling in hands and feet.",
        "Mother may feel more tired; difficulty sleeping.",
        "Increased back pain; difficulty moving.",
        "More frequent fetal movements.",
        "Increased heartburn and indigestion.",
        "Mother may feel more tired; difficulty sleeping.",
        "Increased swelling in hands and feet.",
        "More frequent fetal movements.",
        "Increased back pain; difficulty moving.",
        "Mother may feel more tired; difficulty sleeping.",
        "Increased heartburn and indigestion.",
        "More frequent fetal movements.",
        "Increased swelling in hands and feet.",
        "Mother may feel more tired; difficulty sleeping.",
        "Increased back pain; difficulty moving."
    ],
    "Common Symptoms": [
        "Not technically pregnant yet.",
        "Implantation bleeding.",
        "Morning sickness.",
        "Breast tenderness and frequent urination.",
        "Increased blood volume and hormonal changes.",
        "Uterus expands and weight gain may start.",
        "Increased appetite and possible food cravings.",
        "Belly starts to show and skin changes may occur.",
        "Increased energy levels and reduced morning sickness.",
        "Belly continues to grow and mother may feel fetal movements.",
        "Increased blood flow and possible varicose veins.",
        "Back pain and leg cramps.",
        "Belly becomes more prominent and stretch marks may appear.",
        "Shortness of breath and heartburn.",
        "Belly continues to grow and mother may feel Braxton Hicks contractions.",
        "Swelling in hands and feet.",
        "Mother may feel more tired and have difficulty sleeping.",
        "Belly continues to grow and mother may experience pelvic pain.",
        "Increased vaginal discharge.",
        "More frequent fetal movements.",
        "Increased back pain and difficulty moving.",
        "Mother may feel more tired and have difficulty sleeping.",
        "Increased heartburn and indigestion.",
        "More frequent fetal movements.",
        "Increased swelling in hands and feet.",
        "Mother may feel more tired and have difficulty sleeping.",
        "Increased back pain and difficulty moving.",
        "More frequent fetal movements.",
        "Increased heartburn and indigestion.",
        "Mother may feel more tired and have difficulty sleeping.",
        "Increased swelling in hands and feet.",
        "More frequent fetal movements.",
        "Increased back pain and difficulty moving.",
        "Mother may feel more tired and have difficulty sleeping.",
        "Increased heartburn and indigestion.",
        "More frequent fetal movements.",
        "Increased swelling in hands and feet.",
        "Mother may feel more tired and have difficulty sleeping",
        "Increased back pain and difficulty moving.",
    ]}
max_length = max(len(v) for v in pregnancy_weeks.values())
for key in pregnancy_weeks:
    while len(pregnancy_weeks[key]) < max_length:
        pregnancy_weeks[key].append("")
# Create a DataFrame from the dictionary
df = pd.DataFrame(pregnancy_weeks)

# Save the DataFrame to a CSV file
df.to_csv("detailed_pregnancy_weeks_with_symptoms.csv", index=False)

print("Detailed dataset with common symptoms created and saved as 'detailed_pregnancy_weeks_with_symptoms.csv'.")